name: Test SQL Lambda

on:
  workflow_call:
    inputs:
      pathname:
        required: true
        type: string

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: pg_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install node v14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Setup PG cli
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends postgresql-client
      
    - name: Enable uuid-ossp extension
      run: |
        PGPASSWORD=pg_test psql -U postgres -h 127.0.0.1 -d test_db -c 'CREATE EXTENSION "uuid-ossp";'

    - name: SQL Create table
      run: |
        PGPASSWORD=pg_test psql -U postgres -h 127.0.0.1 -d test_db -f ./table.sql
    
    - name: SQL Add sample data
      run: |
        PGPASSWORD=pg_test psql -U postgres -h 127.0.0.1 -d test_db -f ${{ inputs.pathname }}/test.sql

    - name: Install dependencies
      working-directory: ${{ inputs.pathname }}
      run: npm install

    - name: Test add person
      working-directory: ${{ inputs.pathname }}
      run: npx jest